services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydb?schema=public

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile.front
    ports:
      - '3002:3000'
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
